import "./styles/globals.css"
import {BlitzProvider} from "./blitz-client"

export const metadata = {
  title: {title: "New Blitz App", template: "%s – Blitz"},
  description: "Generated by blitz new ",
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="pt-BR">
      <body className="font-cocogoose antialiased">
        <BlitzProvider>
          <>{children}</>
        </BlitzProvider>
      </body>
    </html>
  )
}

